# copy prod properties here and rename to application-prod.yml to configure prod application properties

server:
  port: 3030
  error:
    include-stacktrace: never

spring:
  application:
    name: GymTrack
  cache:
    type: redis
    redis:
      time-to-live: 60m
  redis:
    host: ip
    port: 1234
    password: pass
  datasource:
    url: jdbc-url
    username: user
    password: pass
  jpa:
    database-platform: org.hibernate.diaclect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    url: 'jdbc-url'
    user: user
    password: pass

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure=ERROR:
#    root: debug