server:
  port: 3030
  error:
    include-message: always
spring:
  application:
    name: GymTrack
  cache:
    type: redis
    redis:
      time-to-live: 60m
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: localhost
    port: 6379
    password: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.diaclect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  flyway:
    enabled: true
    url: 'jdbc:postgresql://localhost:5432/postgres'
    user: admin
    password: admin
    baseline-on-migrate: true

management:
  info:
    env:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

info:
  application:
    name: GymTrack API
    description: Spring Boot REST API for GymTrack application

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure=ERROR:
#    root: debug