# For spinning up local data stores & GUI DB tool (postgres, redis, and pgadmin)
name: GymTrackDB

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  cache:
    container_name: redis
    image: redis:7.0.5-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save "" --appendonly no --loglevel warning --requirepass admin
    # configure redis instance to have no persistence for now
    volumes:
      - cache:/data/redis

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  cache:
